language: php
php:
  - 5.6
before_install:
  - composer self-update
  - composer create-project laravel/laravel
  - cd ./laravel
  - composer require tightenco/mailthief --dev
  - composer config repositories.samkitano vcs https://github.com/samkitano/aktiv8me.git
  - composer require samkitano/aktiv8me dev-master
  - cp ./vendor/samkitano/aktiv8me/tests/config/.env ./
  - rm ./config/app.php
  - rm ./config/database.php
  - rm ./database/factories/ModelFactory.php
  - cp ./vendor/samkitano/aktiv8me/tests/config/app.php ./config
  - cp ./vendor/samkitano/aktiv8me/tests/config/database.php ./config
  - cp ./vendor/samkitano/aktiv8me/tests/config/tests.sqlite ./database
  - cp ./vendor/samkitano/aktiv8me/tests/config/ModelFactory.php ./database/factories
  - cp ./vendor/samkitano/aktiv8me/tests/Feature/DatabaseTest.php ./tests/Feature
  - cp ./vendor/samkitano/aktiv8me/tests/Feature/EmailsTest.php ./tests/Feature
  - cp ./vendor/samkitano/aktiv8me/tests/Unit/Aktiv8meTraitTest.php ./tests/Unit
  - php artisan make:aktiv8me
  - php artisan migrate
  - composer dump-autoload -o
script: "vendor/bin/phpunit"
